### ISSUE TITLE
java.lang.IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by khawarraza-netsoltech** [bosphere/Android-FileLogger#9]
Process: com.companyName.appname, PID: 26026
   java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.companyName.appname/com.bosphere.filelogger.FileLoggerService (has extras) }: app is in background uid UidRecord{64b39ea u0a379 CAC  bg:+3m8s90ms idle procs:1 seq(8288,8288,8288)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.bosphere.filelogger.FileLoggerService.logFile(FileLoggerService.java:51)
       at com.bosphere.filelogger.FL.log(FL.java:133)
       at com.bosphere.filelogger.FL.d(FL.java:46)
       at comcom.companyName.appname.network.HttpAsyncRequest.execute(HttpAsyncRequest.java:175)
       at com.companyName.appname.activities.HomeActivity.sendCurrentLocationToServer(HomeActivity.java:253)
       at com.companyName.appname.activities.HomeActivity.sendCurrentLocation(HomeActivity.java:220)
       at com.companyName.appname.activities.HomeActivity.access$000(HomeActivity.java:67)
       at com.companyName.appname.activities.HomeActivity$2.run(HomeActivity.java:205)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)

This normally happens when application goes to background and app tries to log something. Any idea?

**Comment by bosphere** [comment]
Upgrade to latest version.
